// <auto-generated />
namespace PATIENT_PORTAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FinalMigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalMigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202502130912516_FinalMigrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
